In [8]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/Sql processing on churn.csv")
data_array = df.to_numpy()

In [9]:
data_array

array([['9237-HQITU', 'Female', 0, ..., 70.7, 151.65, 'Yes'],
       ['9305-CDSKC', 'Female', 0, ..., 99.65, 820.5, 'Yes'],
       ['8168-UQWWF', 'Female', 0, ..., 97.85, 1105.4, 'Yes'],
       ...,
       ['1122-JWTJW', 'Male', 0, ..., 70.65, 70.65, 'Yes'],
       ['6894-LFHLY', 'Male', 1, ..., 75.75, 75.75, 'Yes'],
       ['8361-LTMKD', 'Male', 1, ..., 74.4, 306.6, 'Yes']], dtype=object)

In [10]:
data_array = np.nan_to_num(data_array)

In [11]:
monthly = df['MonthlyCharges'].to_numpy()
tenure = df['tenure'].to_numpy()
total = df['TotalCharges'].to_numpy()

In [12]:
data_array

array([['9237-HQITU', 'Female', 0, ..., 70.7, 151.65, 'Yes'],
       ['9305-CDSKC', 'Female', 0, ..., 99.65, 820.5, 'Yes'],
       ['8168-UQWWF', 'Female', 0, ..., 97.85, 1105.4, 'Yes'],
       ...,
       ['1122-JWTJW', 'Male', 0, ..., 70.65, 70.65, 'Yes'],
       ['6894-LFHLY', 'Male', 1, ..., 75.75, 75.75, 'Yes'],
       ['8361-LTMKD', 'Male', 1, ..., 74.4, 306.6, 'Yes']], dtype=object)

In [13]:
avg_monthly = np.mean(monthly)
max_monthly = np.max(monthly)
min_monthly = np.min(monthly)

In [14]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
1,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
2,8168-UQWWF,Female,0,No,No,11,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),97.85,1105.40,Yes
3,7760-OYPDY,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.65,144.15,Yes
4,7495-OOKFY,Female,1,Yes,No,8,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),80.65,633.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,1980-KXVPM,Female,1,No,No,3,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),75.05,256.25,Yes
563,0723-DRCLG,Female,1,Yes,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.45,74.45,Yes
564,1122-JWTJW,Male,0,Yes,Yes,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,70.65,70.65,Yes
565,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
566,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes

In [15]:
avg_spend = total / (tenure + 1)

In [16]:
data_array

array([['9237-HQITU', 'Female', 0, ..., 70.7, 151.65, 'Yes'],
       ['9305-CDSKC', 'Female', 0, ..., 99.65, 820.5, 'Yes'],
       ['8168-UQWWF', 'Female', 0, ..., 97.85, 1105.4, 'Yes'],
       ...,
       ['1122-JWTJW', 'Male', 0, ..., 70.65, 70.65, 'Yes'],
       ['6894-LFHLY', 'Male', 1, ..., 75.75, 75.75, 'Yes'],
       ['8361-LTMKD', 'Male', 1, ..., 74.4, 306.6, 'Yes']], dtype=object)

In [17]:
charge_group = np.where(monthly < 50, "Low",
                np.where(monthly < 80, "Medium", "High"))

In [18]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
1,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
2,8168-UQWWF,Female,0,No,No,11,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),97.85,1105.40,Yes
3,7760-OYPDY,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.65,144.15,Yes
4,7495-OOKFY,Female,1,Yes,No,8,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),80.65,633.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,1980-KXVPM,Female,1,No,No,3,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),75.05,256.25,Yes
563,0723-DRCLG,Female,1,Yes,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.45,74.45,Yes
564,1122-JWTJW,Male,0,Yes,Yes,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,70.65,70.65,Yes
565,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
566,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes

In [19]:
df['TotalCharges']

0       151.65
1       820.50
2      1105.40
3       144.15
4       633.30
        ...
562     256.25
563      74.45
564      70.65
565      75.75
566     306.60
Name: TotalCharges, Length: 567, dtype: float64

In [22]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})

In [23]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,9237-HQITU,0,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
1,9305-CDSKC,0,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
2,8168-UQWWF,0,0,No,No,11,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),97.85,1105.40,Yes
3,7760-OYPDY,0,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.65,144.15,Yes
4,7495-OOKFY,0,1,Yes,No,8,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),80.65,633.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,1980-KXVPM,0,1,No,No,3,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),75.05,256.25,Yes
563,0723-DRCLG,0,1,Yes,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.45,74.45,Yes
564,1122-JWTJW,1,0,Yes,Yes,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,70.65,70.65,Yes
565,6894-LFHLY,1,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
566,8361-LTMKD,1,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes

In [26]:
df['Contract'] = df['Contract'].astype('category').cat.codes

In [27]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,9237-HQITU,0,0,No,No,2,Yes,No,1,No,...,No,No,No,No,0,Yes,Electronic check,70.70,151.65,Yes
1,9305-CDSKC,0,0,No,No,8,Yes,Yes,1,No,...,Yes,No,Yes,Yes,0,Yes,Electronic check,99.65,820.50,Yes
2,8168-UQWWF,0,0,No,No,11,Yes,Yes,1,No,...,Yes,No,Yes,Yes,0,Yes,Bank transfer (automatic),97.85,1105.40,Yes
3,7760-OYPDY,0,0,No,No,2,Yes,No,1,No,...,No,No,Yes,No,0,Yes,Electronic check,80.65,144.15,Yes
4,7495-OOKFY,0,1,Yes,No,8,Yes,Yes,1,No,...,No,No,No,No,0,Yes,Credit card (automatic),80.65,633.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,1980-KXVPM,0,1,No,No,3,Yes,Yes,1,No,...,No,No,No,No,0,Yes,Credit card (automatic),75.05,256.25,Yes
563,0723-DRCLG,0,1,Yes,No,1,Yes,Yes,1,No,...,No,No,No,No,0,Yes,Electronic check,74.45,74.45,Yes
564,1122-JWTJW,1,0,Yes,Yes,1,Yes,No,1,No,...,No,No,No,No,0,Yes,Mailed check,70.65,70.65,Yes
565,6894-LFHLY,1,1,No,No,1,Yes,Yes,1,No,...,No,No,No,No,0,Yes,Electronic check,75.75,75.75,Yes
566,8361-LTMKD,1,1,Yes,No,4,Yes,Yes,1,No,...,No,No,No,No,0,Yes,Mailed check,74.40,306.60,Yes

In [28]:
df['InternetService'] = df['InternetService'].map({
    'DSL': 0,
    'Fiber optic': 1,
    'No': 2
})

In [29]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,9237-HQITU,0,0,No,No,2,Yes,No,NaN,No,...,No,No,No,No,0,Yes,Electronic check,70.70,151.65,Yes
1,9305-CDSKC,0,0,No,No,8,Yes,Yes,NaN,No,...,Yes,No,Yes,Yes,0,Yes,Electronic check,99.65,820.50,Yes
2,8168-UQWWF,0,0,No,No,11,Yes,Yes,NaN,No,...,Yes,No,Yes,Yes,0,Yes,Bank transfer (automatic),97.85,1105.40,Yes
3,7760-OYPDY,0,0,No,No,2,Yes,No,NaN,No,...,No,No,Yes,No,0,Yes,Electronic check,80.65,144.15,Yes
4,7495-OOKFY,0,1,Yes,No,8,Yes,Yes,NaN,No,...,No,No,No,No,0,Yes,Credit card (automatic),80.65,633.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,1980-KXVPM,0,1,No,No,3,Yes,Yes,NaN,No,...,No,No,No,No,0,Yes,Credit card (automatic),75.05,256.25,Yes
563,0723-DRCLG,0,1,Yes,No,1,Yes,Yes,NaN,No,...,No,No,No,No,0,Yes,Electronic check,74.45,74.45,Yes
564,1122-JWTJW,1,0,Yes,Yes,1,Yes,No,NaN,No,...,No,No,No,No,0,Yes,Mailed check,70.65,70.65,Yes
565,6894-LFHLY,1,1,No,No,1,Yes,Yes,NaN,No,...,No,No,No,No,0,Yes,Electronic check,75.75,75.75,Yes
566,8361-LTMKD,1,1,Yes,No,4,Yes,Yes,NaN,No,...,No,No,No,No,0,Yes,Mailed check,74.40,306.60,Yes